// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnrichmentRequest {
    #[prost(string, repeated, tag = "1")]
    pub isbns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditionIdentityRequest {
    #[prost(message, repeated, tag = "1")]
    pub queries: ::prost::alloc::vec::Vec<EditionIdentityQuery>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EditionIdentityQuery {
    #[prost(string, tag = "1")]
    pub query_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub publishers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(sint32, optional, tag = "5")]
    pub book_year: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditionIdentityResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<Snapshot>,
    #[prost(message, repeated, tag = "2")]
    pub results: ::prost::alloc::vec::Vec<EditionIdentityResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditionIdentityResult {
    #[prost(string, tag = "1")]
    pub query_id: ::prost::alloc::string::String,
    #[prost(enumeration = "EditionIdentityStatus", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub matched: ::core::option::Option<EditionIdentityMatch>,
    #[prost(message, repeated, tag = "4")]
    pub candidates: ::prost::alloc::vec::Vec<EditionIdentityMatch>,
    #[prost(bool, tag = "5")]
    pub candidates_truncated: bool,
    #[prost(message, optional, tag = "6")]
    pub authority_subjects: ::core::option::Option<AuthoritySubjectMatch>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditionIdentityMatch {
    #[prost(string, tag = "1")]
    pub canonical_isbn13: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub open_library_edition_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub open_library_work_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub work_title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "EditionTitleMatch", tag = "6")]
    pub title_match: i32,
    #[prost(string, repeated, tag = "7")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "8")]
    pub publishers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(sint32, optional, tag = "9")]
    pub book_year: ::core::option::Option<i32>,
    #[prost(bool, tag = "10")]
    pub matched_publisher: bool,
    #[prost(bool, tag = "11")]
    pub matched_book_year: bool,
    #[prost(message, repeated, tag = "12")]
    pub classifications: ::prost::alloc::vec::Vec<Classification>,
    #[prost(string, optional, tag = "13")]
    pub subtitle: ::core::option::Option<::prost::alloc::string::String>,

}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnrichmentResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<Snapshot>,
    #[prost(message, repeated, tag = "2")]
    pub results: ::prost::alloc::vec::Vec<IsbnResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Snapshot {
    #[prost(string, tag = "1")]
    pub dump_date: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub imported_at_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IsbnResult {
    #[prost(message, repeated, tag = "5")]
    pub wikidata_books: ::prost::alloc::vec::Vec<crate::wikidata::WikidataBookEvidence>,
    #[prost(string, tag = "1")]
    pub requested_isbn: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub canonical_isbn13: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "LookupStatus", tag = "3")]
    pub status: i32,
    #[prost(message, repeated, tag = "4")]
    pub matches: ::prost::alloc::vec::Vec<WorkMatch>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkMatch {
    #[prost(string, optional, tag = "1")]
    pub open_library_work_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub exact_edition_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub classifications: ::prost::alloc::vec::Vec<Classification>,
    #[prost(message, repeated, tag = "4")]
    pub authors: ::prost::alloc::vec::Vec<Author>,
    /// Plain-text Open Library work description, when the snapshot has one.
    #[prost(string, optional, tag = "8")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "9")]
    pub subjects: ::prost::alloc::vec::Vec<SubjectHeading>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubjectHeading {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub components: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub authority_uri: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Classification {
    #[prost(message, repeated, tag = "4")]
    pub evidence: ::prost::alloc::vec::Vec<ClassificationEvidence>,
    #[prost(enumeration = "ClassificationScheme", tag = "1")]
    pub scheme: i32,
    #[prost(string, tag = "2")]
    pub notation: ::prost::alloc::string::String,
    #[prost(enumeration = "ClassificationSource", tag = "3")]
    pub source: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Author {
    #[prost(string, tag = "1")]
    pub open_library_author_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub identifiers: ::prost::alloc::vec::Vec<AuthorIdentifier>,
    #[prost(enumeration = "AuthorSource", tag = "4")]
    pub source: i32,
    #[prost(uint32, tag = "5")]
    pub position: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthorIdentifier {
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LookupStatus {
    Unspecified = 0,
    Matched = 1,
    NoMatch = 2,
    InvalidIsbn = 3,
    Ambiguous = 4,
}
impl LookupStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LOOKUP_STATUS_UNSPECIFIED",
            Self::Matched => "LOOKUP_STATUS_MATCHED",
            Self::NoMatch => "LOOKUP_STATUS_NO_MATCH",
            Self::InvalidIsbn => "LOOKUP_STATUS_INVALID_ISBN",
            Self::Ambiguous => "LOOKUP_STATUS_AMBIGUOUS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOOKUP_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "LOOKUP_STATUS_MATCHED" => Some(Self::Matched),
            "LOOKUP_STATUS_NO_MATCH" => Some(Self::NoMatch),
            "LOOKUP_STATUS_INVALID_ISBN" => Some(Self::InvalidIsbn),
            "LOOKUP_STATUS_AMBIGUOUS" => Some(Self::Ambiguous),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EditionIdentityStatus {
    Unspecified = 0,
    Matched = 1,
    NoMatch = 2,
    Ambiguous = 3,
    InsufficientMetadata = 4,
}
impl EditionIdentityStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EDITION_IDENTITY_STATUS_UNSPECIFIED",
            Self::Matched => "EDITION_IDENTITY_STATUS_MATCHED",
            Self::NoMatch => "EDITION_IDENTITY_STATUS_NO_MATCH",
            Self::Ambiguous => "EDITION_IDENTITY_STATUS_AMBIGUOUS",
            Self::InsufficientMetadata => "EDITION_IDENTITY_STATUS_INSUFFICIENT_METADATA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EDITION_IDENTITY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "EDITION_IDENTITY_STATUS_MATCHED" => Some(Self::Matched),
            "EDITION_IDENTITY_STATUS_NO_MATCH" => Some(Self::NoMatch),
            "EDITION_IDENTITY_STATUS_AMBIGUOUS" => Some(Self::Ambiguous),
            "EDITION_IDENTITY_STATUS_INSUFFICIENT_METADATA" => Some(Self::InsufficientMetadata),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EditionTitleMatch {
    Unspecified = 0,
    Edition = 1,
    Work = 2,
    Both = 3,
}
impl EditionTitleMatch {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EDITION_TITLE_MATCH_UNSPECIFIED",
            Self::Edition => "EDITION_TITLE_MATCH_EDITION",
            Self::Work => "EDITION_TITLE_MATCH_WORK",
            Self::Both => "EDITION_TITLE_MATCH_BOTH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EDITION_TITLE_MATCH_UNSPECIFIED" => Some(Self::Unspecified),
            "EDITION_TITLE_MATCH_EDITION" => Some(Self::Edition),
            "EDITION_TITLE_MATCH_WORK" => Some(Self::Work),
            "EDITION_TITLE_MATCH_BOTH" => Some(Self::Both),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClassificationScheme {
    Unspecified = 0,
    LibraryOfCongress = 1,
    DeweyDecimal = 2,
    Bisac = 3,
}
impl ClassificationScheme {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CLASSIFICATION_SCHEME_UNSPECIFIED",
            Self::LibraryOfCongress => "CLASSIFICATION_SCHEME_LIBRARY_OF_CONGRESS",
            Self::DeweyDecimal => "CLASSIFICATION_SCHEME_DEWEY_DECIMAL",
            Self::Bisac => "CLASSIFICATION_SCHEME_BISAC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CLASSIFICATION_SCHEME_UNSPECIFIED" => Some(Self::Unspecified),
            "CLASSIFICATION_SCHEME_LIBRARY_OF_CONGRESS" => Some(Self::LibraryOfCongress),
            "CLASSIFICATION_SCHEME_DEWEY_DECIMAL" => Some(Self::DeweyDecimal),
            "CLASSIFICATION_SCHEME_BISAC" => Some(Self::Bisac),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClassificationSource {
    Unspecified = 0,
    ExactEdition = 1,
    Work = 2,
}
impl ClassificationSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CLASSIFICATION_SOURCE_UNSPECIFIED",
            Self::ExactEdition => "CLASSIFICATION_SOURCE_EXACT_EDITION",
            Self::Work => "CLASSIFICATION_SOURCE_WORK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CLASSIFICATION_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "CLASSIFICATION_SOURCE_EXACT_EDITION" => Some(Self::ExactEdition),
            "CLASSIFICATION_SOURCE_WORK" => Some(Self::Work),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuthorSource {
    Unspecified = 0,
    ExactEdition = 1,
    Work = 2,
}
impl AuthorSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUTHOR_SOURCE_UNSPECIFIED",
            Self::ExactEdition => "AUTHOR_SOURCE_EXACT_EDITION",
            Self::Work => "AUTHOR_SOURCE_WORK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTHOR_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "AUTHOR_SOURCE_EXACT_EDITION" => Some(Self::ExactEdition),
            "AUTHOR_SOURCE_WORK" => Some(Self::Work),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClassificationEvidence {
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub isbn13: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub open_library_work_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub open_library_edition_id: ::prost::alloc::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthoritySubjectMatch {
    #[prost(string, tag = "6")]
    pub main_title: String,
    #[prost(string, tag = "1")]
    pub provider_id: String,
    #[prost(string, repeated, tag = "2")]
    pub record_ids: Vec<String>,
    #[prost(string, tag = "3")]
    pub title: String,
    #[prost(string, repeated, tag = "4")]
    pub authors: Vec<String>,
    #[prost(message, repeated, tag = "5")]
    pub classifications: Vec<Classification>,
}
