[package]
name = "thumbnail"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["book-extractors"]
book-memory = ["dep:epub_provider", "dep:mobi", "dep:resvg"]
book-extractors = ["book-memory", "dep:mp4ameta"]

[dependencies]
moxcms = { version = "0.8.1" }
hayro-jpeg2000 = { version = "0.4.0", default-features = false, features = ["std"] }
jpeg-decoder = { version = "0.3.2", default-features = false }
lopdf = { version = "0.44", default-features = false }
pdf-range-reader = { path = "../../../../shared/pdf-range-reader" }
audiobook-folder = { path = "../../../../shared/audiobook-folder" }
zip.workspace = true
epub_provider = { path = "../../../../shared/epub", optional = true }
fast_image_resize = { version = "5.2.0", features = ["image"] }
image = { version = "0.24.9", default-features = false, features = ["bmp", "gif", "jpeg", "png", "webp"] }
mobi = { workspace = true, optional = true }
mp4ameta = { version = "0.13.0", optional = true }
pdf-reader-core = { path = "../../../../shared/pdf-reader-core" }
resvg = { version = "0.46.0", optional = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tempfile = "3"
