// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(oneof = "value::Kind", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15")]
    pub kind: ::core::option::Option<value::Kind>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(bool, tag = "1")]
        BoolValue(bool),
        #[prost(uint32, tag = "2")]
        U32Value(u32),
        #[prost(uint64, tag = "3")]
        U64Value(u64),
        #[prost(sint32, tag = "4")]
        I32Value(i32),
        #[prost(sint64, tag = "5")]
        I64Value(i64),
        #[prost(fixed32, tag = "6")]
        F32Bits(u32),
        #[prost(fixed64, tag = "7")]
        F64Bits(u64),
        #[prost(uint32, tag = "8")]
        CharValue(u32),
        #[prost(string, tag = "9")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "10")]
        Unit(super::Unit),
        #[prost(message, tag = "11")]
        OptionValue(::prost::alloc::boxed::Box<super::OptionalValue>),
        #[prost(message, tag = "12")]
        NewtypeValue(::prost::alloc::boxed::Box<super::Value>),
        #[prost(message, tag = "13")]
        Sequence(super::Sequence),
        #[prost(message, tag = "14")]
        Map(super::Map),
        #[prost(bytes, tag = "15")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Unit {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptionalValue {
    #[prost(message, optional, boxed, tag = "1")]
    pub value: ::core::option::Option<::prost::alloc::boxed::Box<Value>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sequence {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Map {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapEntry {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<Value>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<Value>,
}
/// Typed payload carried by WireMutation.value. These field numbers and enum
/// values form the mutation compatibility baseline: never renumber or reuse
/// them. Additive fields must remain optional or have a safe zero default.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MutationValue {
    #[prost(oneof = "mutation_value::Kind", tags = "1, 2, 3, 4, 5, 6, 7, 11, 12, 13, 14, 15")]
    pub kind: ::core::option::Option<mutation_value::Kind>,
}
/// Nested message and enum types in `MutationValue`.
pub mod mutation_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(string, tag = "1")]
        DirectoryName(::prost::alloc::string::String),
        #[prost(string, tag = "2")]
        DirectoryParent(::prost::alloc::string::String),
        #[prost(enumeration = "super::DirectoryLifecycle", tag = "3")]
        DirectoryLifecycle(i32),
        #[prost(message, tag = "4")]
        BookLifecycle(super::BookLifecycle),
        #[prost(message, tag = "5")]
        Placement(super::Placement),
        #[prost(message, tag = "6")]
        ReadingPosition(super::ReadingPosition),
        #[prost(message, tag = "7")]
        Annotation(super::Annotation),
        #[prost(message, tag = "11")]
        Metadata(super::BookRecord),
        #[prost(string, tag = "12")]
        Description(::prost::alloc::string::String),
        #[prost(bytes, tag = "13")]
        PdfReaderMetadata(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes, tag = "14")]
        BookToc(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "15")]
        BookFacts(super::BookFacts),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookLifecycle {
    #[prost(oneof = "book_lifecycle::State", tags = "1, 2, 3")]
    pub state: ::core::option::Option<book_lifecycle::State>,
}
/// Nested message and enum types in `BookLifecycle`.
pub mod book_lifecycle {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum State {
        #[prost(message, tag = "1")]
        Present(super::PresentBook),
        #[prost(message, tag = "2")]
        Deleted(super::DeletedBook),
        #[prost(message, tag = "3")]
        Purged(super::PurgedBook),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PresentBook {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookFacts {
    #[prost(uint64, tag = "1")]
    pub added_at: u64,
    #[prost(enumeration = "BookFormat", tag = "2")]
    pub format: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletedBook {
    #[prost(string, optional, tag = "1")]
    pub origin_folder_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PurgedBook {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Placement {
    #[prost(bool, tag = "1")]
    pub present: bool,
    #[prost(string, optional, tag = "2")]
    pub origin_folder_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadingPosition {
    #[prost(float, tag = "4")]
    pub progress: f32,
    #[prost(oneof = "reading_position::Location", tags = "1, 2, 3")]
    pub location: ::core::option::Option<reading_position::Location>,
    #[prost(float, optional, tag = "5")]
    pub pdf_full_page_position: ::core::option::Option<f32>,
}
/// Nested message and enum types in `ReadingPosition`.
pub mod reading_position {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Location {
        #[prost(string, tag = "1")]
        EpubCfi(::prost::alloc::string::String),
        #[prost(uint32, tag = "2")]
        PdfPage(u32),
        #[prost(uint64, tag = "3")]
        AudiobookMillis(u64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Annotation {
    #[prost(string, tag = "1")]
    pub content_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub anchor: ::core::option::Option<AnnotationAnchor>,
    #[prost(string, tag = "3")]
    pub exact_text: ::prost::alloc::string::String,
    #[prost(enumeration = "AnnotationStyle", tag = "4")]
    pub style: i32,
    #[prost(string, tag = "5")]
    pub color: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub note: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub created_at: u64,
    #[prost(uint64, tag = "8")]
    pub modified_at: u64,
    #[prost(bool, tag = "9")]
    pub deleted: bool,
    #[prost(int64, optional, tag = "10")]
    pub toc_ordinal: ::core::option::Option<i64>,
    #[prost(float, optional, tag = "11")]
    pub progress: ::core::option::Option<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnnotationAnchor {
    #[prost(oneof = "annotation_anchor::Anchor", tags = "1, 2")]
    pub anchor: ::core::option::Option<annotation_anchor::Anchor>,
}
/// Nested message and enum types in `AnnotationAnchor`.
pub mod annotation_anchor {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Anchor {
        #[prost(string, tag = "1")]
        EpubCfi(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Pdf(super::PdfAnnotationAnchor),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PdfAnnotationAnchor {
    #[prost(uint32, tag = "1")]
    pub page_index: u32,
    #[prost(message, repeated, tag = "2")]
    pub rects: ::prost::alloc::vec::Vec<PdfAnnotationRect>,
    #[prost(string, optional, tag = "3")]
    pub fallback_cfi: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PdfAnnotationRect {
    #[prost(float, tag = "1")]
    pub left: f32,
    #[prost(float, tag = "2")]
    pub top: f32,
    #[prost(float, tag = "3")]
    pub width: f32,
    #[prost(float, tag = "4")]
    pub height: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookRecord {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub contributors: ::prost::alloc::vec::Vec<Contributor>,
    #[prost(message, optional, tag = "4")]
    pub book: ::core::option::Option<BookMetadata>,
    #[prost(string, optional, tag = "5")]
    pub subtitle: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Contributor {
    #[prost(string, tag = "1")]
    pub contributor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub role: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookMetadata {
    #[prost(message, repeated, tag = "1")]
    pub identifiers: ::prost::alloc::vec::Vec<BookIdentifier>,
    #[prost(message, repeated, tag = "2")]
    pub publishers: ::prost::alloc::vec::Vec<Publisher>,
    #[prost(string, repeated, tag = "3")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub dates: ::prost::alloc::vec::Vec<BookDate>,
    #[prost(message, repeated, tag = "5")]
    pub subjects: ::prost::alloc::vec::Vec<BookSubject>,
    #[prost(message, repeated, tag = "6")]
    pub collections: ::prost::alloc::vec::Vec<BookCollection>,
    #[prost(message, repeated, tag = "7")]
    pub alternate_titles: ::prost::alloc::vec::Vec<BookTitle>,
    #[prost(string, repeated, tag = "8")]
    pub rights: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "9")]
    pub sources: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "10")]
    pub types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "11")]
    pub formats: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "12")]
    pub relations: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "13")]
    pub coverage: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "14")]
    pub properties: ::prost::alloc::vec::Vec<BookProperty>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookIdentifier {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
    #[prost(enumeration = "IdentifierScheme", tag = "2")]
    pub scheme: i32,
    #[prost(string, optional, tag = "3")]
    pub other_scheme: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub identifier_types: ::prost::alloc::vec::Vec<BookIdentifierType>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookIdentifierType {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub scheme: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Publisher {
    #[prost(string, tag = "1")]
    pub publisher_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookDate {
    #[prost(string, optional, tag = "1")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub event: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookSubject {
    #[prost(string, optional, tag = "1")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub authority: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "6")]
    pub name_localizations: ::prost::alloc::vec::Vec<LocalizedText>,
    #[prost(string, optional, tag = "7")]
    pub sort_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "8")]
    pub sort_name_localizations: ::prost::alloc::vec::Vec<LocalizedText>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookCollection {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub collection_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub position: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub name_localizations: ::prost::alloc::vec::Vec<LocalizedText>,
    #[prost(string, optional, tag = "5")]
    pub sort_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "6")]
    pub sort_name_localizations: ::prost::alloc::vec::Vec<LocalizedText>,
    #[prost(string, repeated, tag = "7")]
    pub identifiers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LocalizedText {
    #[prost(string, tag = "1")]
    pub language: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookTitle {
    #[prost(string, optional, tag = "1")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub title_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub sort_as: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BookProperty {
    #[prost(string, optional, tag = "1")]
    pub id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub property: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub refines: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub scheme: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DirectoryLifecycle {
    Unspecified = 0,
    Present = 1,
    Deleted = 2,
    Purged = 3,
}
impl DirectoryLifecycle {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DIRECTORY_LIFECYCLE_UNSPECIFIED",
            Self::Present => "DIRECTORY_LIFECYCLE_PRESENT",
            Self::Deleted => "DIRECTORY_LIFECYCLE_DELETED",
            Self::Purged => "DIRECTORY_LIFECYCLE_PURGED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECTORY_LIFECYCLE_UNSPECIFIED" => Some(Self::Unspecified),
            "DIRECTORY_LIFECYCLE_PRESENT" => Some(Self::Present),
            "DIRECTORY_LIFECYCLE_DELETED" => Some(Self::Deleted),
            "DIRECTORY_LIFECYCLE_PURGED" => Some(Self::Purged),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BookFormat {
    Unspecified = 0,
    Epub = 1,
    Pdf = 2,
    Mobi = 3,
    Fb2 = 4,
    Cbz = 5,
    Html = 6,
    Webpub = 7,
    M4b = 8,
    Mp3Folder = 9,
}
impl BookFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BOOK_FORMAT_UNSPECIFIED",
            Self::Epub => "BOOK_FORMAT_EPUB",
            Self::Pdf => "BOOK_FORMAT_PDF",
            Self::Mobi => "BOOK_FORMAT_MOBI",
            Self::Fb2 => "BOOK_FORMAT_FB2",
            Self::Cbz => "BOOK_FORMAT_CBZ",
            Self::Html => "BOOK_FORMAT_HTML",
            Self::Webpub => "BOOK_FORMAT_WEBPUB",
            Self::M4b => "BOOK_FORMAT_M4B",
            Self::Mp3Folder => "BOOK_FORMAT_MP3_FOLDER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BOOK_FORMAT_UNSPECIFIED" => Some(Self::Unspecified),
            "BOOK_FORMAT_EPUB" => Some(Self::Epub),
            "BOOK_FORMAT_PDF" => Some(Self::Pdf),
            "BOOK_FORMAT_MOBI" => Some(Self::Mobi),
            "BOOK_FORMAT_FB2" => Some(Self::Fb2),
            "BOOK_FORMAT_CBZ" => Some(Self::Cbz),
            "BOOK_FORMAT_HTML" => Some(Self::Html),
            "BOOK_FORMAT_WEBPUB" => Some(Self::Webpub),
            "BOOK_FORMAT_M4B" => Some(Self::M4b),
            "BOOK_FORMAT_MP3_FOLDER" => Some(Self::Mp3Folder),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AnnotationStyle {
    Unspecified = 0,
    Highlight = 1,
    Underline = 2,
    Squiggly = 3,
    Strikethrough = 4,
}
impl AnnotationStyle {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ANNOTATION_STYLE_UNSPECIFIED",
            Self::Highlight => "ANNOTATION_STYLE_HIGHLIGHT",
            Self::Underline => "ANNOTATION_STYLE_UNDERLINE",
            Self::Squiggly => "ANNOTATION_STYLE_SQUIGGLY",
            Self::Strikethrough => "ANNOTATION_STYLE_STRIKETHROUGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ANNOTATION_STYLE_UNSPECIFIED" => Some(Self::Unspecified),
            "ANNOTATION_STYLE_HIGHLIGHT" => Some(Self::Highlight),
            "ANNOTATION_STYLE_UNDERLINE" => Some(Self::Underline),
            "ANNOTATION_STYLE_SQUIGGLY" => Some(Self::Squiggly),
            "ANNOTATION_STYLE_STRIKETHROUGH" => Some(Self::Strikethrough),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IdentifierScheme {
    Unspecified = 0,
    Isbn = 1,
    Asin = 2,
    Doi = 3,
    Issn = 4,
    Oclc = 5,
    Lccn = 6,
    Uuid = 7,
    Calibre = 8,
    Google = 9,
    Goodreads = 10,
    Kobo = 11,
    Other = 12,
}
impl IdentifierScheme {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "IDENTIFIER_SCHEME_UNSPECIFIED",
            Self::Isbn => "IDENTIFIER_SCHEME_ISBN",
            Self::Asin => "IDENTIFIER_SCHEME_ASIN",
            Self::Doi => "IDENTIFIER_SCHEME_DOI",
            Self::Issn => "IDENTIFIER_SCHEME_ISSN",
            Self::Oclc => "IDENTIFIER_SCHEME_OCLC",
            Self::Lccn => "IDENTIFIER_SCHEME_LCCN",
            Self::Uuid => "IDENTIFIER_SCHEME_UUID",
            Self::Calibre => "IDENTIFIER_SCHEME_CALIBRE",
            Self::Google => "IDENTIFIER_SCHEME_GOOGLE",
            Self::Goodreads => "IDENTIFIER_SCHEME_GOODREADS",
            Self::Kobo => "IDENTIFIER_SCHEME_KOBO",
            Self::Other => "IDENTIFIER_SCHEME_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IDENTIFIER_SCHEME_UNSPECIFIED" => Some(Self::Unspecified),
            "IDENTIFIER_SCHEME_ISBN" => Some(Self::Isbn),
            "IDENTIFIER_SCHEME_ASIN" => Some(Self::Asin),
            "IDENTIFIER_SCHEME_DOI" => Some(Self::Doi),
            "IDENTIFIER_SCHEME_ISSN" => Some(Self::Issn),
            "IDENTIFIER_SCHEME_OCLC" => Some(Self::Oclc),
            "IDENTIFIER_SCHEME_LCCN" => Some(Self::Lccn),
            "IDENTIFIER_SCHEME_UUID" => Some(Self::Uuid),
            "IDENTIFIER_SCHEME_CALIBRE" => Some(Self::Calibre),
            "IDENTIFIER_SCHEME_GOOGLE" => Some(Self::Google),
            "IDENTIFIER_SCHEME_GOODREADS" => Some(Self::Goodreads),
            "IDENTIFIER_SCHEME_KOBO" => Some(Self::Kobo),
            "IDENTIFIER_SCHEME_OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
